### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by Jonas-Verhellen** [FreyrS/dMaSIF#1]
Would it be possible to provide a conda [environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment) for this project? Would make trying the package out significantly more easy. Thanks for the great project. 

Kind regards,
Jonas

**Comment by jeanfeydy** [comment]
Hi @Jonas-Verhellen ,

Thanks for your interest in dMaSIF!
You may find [here](https://gist.github.com/jeanfeydy/d9395912e4d8bf1c0340bc93f78ea4bd) the conda environment that I am currently using to run our experiments (I don't know if @FreyrS uses conda on his machine). Note, however, that it is far from being a minimal environment, and I wouldn't recommend you to clone it as is.

To run dMaSIF on your computer, the main stumbling block is likely to be the **installation of the [KeOps library](https://www.kernel-operations.io), which is described [here](https://www.kernel-operations.io/keops/python/installation.html)**. We are currently working on streamlining this process with a lighter compilation engine, but a hard dependency on a full CUDA environment (with g++ and nvcc available in the path) is likely to remain until the summer. 
Unfortunately, a conda recipe for KeOps is not available yet... but if you experience issues with the installation, you may find some information [here](https://github.com/getkeops/keops/issues/107). Of course, please feel free to open an issue on the [KeOps repo](https://github.com/getkeops/keops/issues/107) if things don't go as expected.

Once KeOps is installed and [working as expected](https://www.kernel-operations.io/keops/python/installation.html#testing-your-installation), installing a recent version of PyTorch and PyTorch_geometric should then allow you to run the models!
Did you succeed in making it work on your side?

Best regards,
Jean

**Comment by FreyrS** [comment]
Note also that in my experience the trickiest part is to install compatible versions of pytorch, pytorch_geometric and keops. I've added a requirements file for the pip environment I've been using.

**Comment by Jonas-Verhellen** [comment]
Thank you for the extensive answer!

It seems to be working now, however I can you tell me where to download the dataset from? Right now it seems to be hard-coded to "". I get the following error: `:Dataset not found. Please download protein_surfaces.tar.gz from  and move it to surface_data/raw`

Thanks again for the swift response and the great work.

**Comment by FreyrS** [comment]
Hi @Jonas-Verhellen 
Sorry for the late response. I've updated the Dataset now so it downloads and processes the data as necessary.
