### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by Guolei-Jian** [FreyrS/dMaSIF#10]
thanks for your great work! But I am in trouble when I run a sctipt in benchmark_scripts.   
I do not change anything, but simply run the `python -W ignore -u main_training.py --experiment_name dMaSIF_search_1layer_12A --batch_size 64 --embedding_layer dMaSIF --search True --device cuda:0 --random_rotation True --radius 12.0 --n_layers 1` . The terminal show me an error `tarfile.ReadError: file could not be opened successfully` . The code is `tar = tarfile.open(self.raw_paths[0])` in data.py.   
How could solve the problem?

**Comment by sarora11** [comment]
Have you tried deleting the `surface_data` directory and rerunning? That has worked in my experience, it is possible the full tarfile did not download successfully, rendering it unreadable.
