### ISSUE TITLE
Benchmark experiments for site and single protein cannot run. 

### ISSUE THREAD

**Issue by YannisBilly** [FreyrS/dMaSIF#12]
Tried to run the benchmark experiments. Resulted in a dict call of a None Type.

Through code reviewing, I saw the following function:

https://github.com/FreyrS/dMaSIF/blob/master/data_iteration.py#:~:text=def%20iterate_surface_precompute(dataset,return%20processed_dataset

where if single protein is passed as True, P2 is still called like a regular Dict where it is of type None from:

https://github.com/FreyrS/dMaSIF/blob/0dcc26c3c218a39d5fe26beb2e788b95fb028896/data_iteration.py#:~:text=def%20process(args,return%20P1%2C%20P2

**Comment by sarora11** [comment]
I have a fix in `iterate_surface_precompute`. Simply put the references to `P2` in an if statement for single protein. Replace L447-450 in `data_iteration.py` with below.

```
if not args.single_protein: 
        protein_pair.gen_xyz_p2 = P2["xyz"]
        protein_pair.gen_normals_p2 = P2["normals"]
        protein_pair.gen_batch_p2 = P2["batch"]
        protein_pair.gen_labels_p2 = P2["labels"]
```
