### ISSUE TITLE
Models available for benchmarking

### ISSUE THREAD

**Issue by sarora11** [FreyrS/dMaSIF#13]
Will other models for the benchmark scripts be made available? Currently only dMaSIF_search_3layer_12A_16dim is in the models directory.

**Comment by lemairecarl** [comment]
I agree. (See https://github.com/FreyrS/dMaSIF/issues/16)

**Comment by FreyrS** [comment]
Hi @sarora11,

dMaSIF has now been made easier to use through Google Colab, please check https://colab.research.google.com/github/casperg92/MaSIF_colab/blob/main/dMaSIF_Colab_V1.ipynb and see if it helps

**Comment by lemairecarl** [comment]
Hi, thanks a lot for this, it is helpful.

However, I do not agree with closing this issue, as we don't have appropriate weights for dMaSIF search.
