### ISSUE TITLE
tutorial and use case

### ISSUE THREAD

**Issue by jflucier** [FreyrS/dMaSIF#15]
Hello,

i was wandering if it would be possible to provide documentation on how tu use dMaSIF.

What command needs to be performed for example to run main_inference.py site for PLD1 (4ZQK.pdb)

Also more details on how to predict interactome using main_inference.py search for PLD1 would be greatly appreciated.

If you provide a script for each of theses usecases would greatly help understanding how to operate the software.

This software would be very usefull for our group. We would like to find the interactome of many new proteins we have detected by MS and predicted structure using Alphafold.

Thank you very much in advance for your help.

**Comment by zshyang** [comment]
Hi @jflucier 

Did you make any progress on your project? I am also at the beginning of trying to reproduce some results from this repo. It would be great if we could have some discussion together.

Best regards

**Comment by lemairecarl** [comment]
@zshyang I sent you an email

**Comment by Max1461** [comment]
Hello everyone,

I`ve been able to use the provided data to run dMaSIF and reproduce the results, but would like to use dMaSIF to train a model on a new dataset. We have protein structure data in pdb files for known interactions. I saw these posts and wondered if any of you had been able to use dMaSIF to train on a new dataset and have any insights to share in how to get this to work.

Thanks for your time and help in advance.

**Comment by FreyrS** [comment]
Hi @jflucier,

dMaSIF has now been made easier to use through Google Colab, please check https://colab.research.google.com/github/casperg92/MaSIF_colab/blob/main/dMaSIF_Colab_V1.ipynb and see if it helps

**Comment by lemairecarl** [comment]
Hi, thanks a lot for this, it is helpful.

However, I do not agree with closing this issue, as we don't have appropriate weights for dMaSIF search.

**Comment by zyzheng17** [comment]
Hi,@Max1461

Could you please tell us how to use the main_inference.py for a single pdb(xxxx.pdb)? We are stuck on this problem.

Thanks for your time and help in advance.

**Comment by brspurri** [comment]
I'm trying to figure out how to run `main_interface.py` on a single PDB as well. No luck as of yet.

**Comment by Amin-Debabeche** [comment]
Hey,  just to let you know that on the google collab (dMaSIF_Colab_V1.ipynb) there are minor changes to do : 
- !pip install torch==1.13.1 (compatible version including deprecetad torch._six)
- from MaSIF_colab.data_preprocessing.download_pdb import convert_to_npy (import issues)

**Comment by orange2350** [comment]
@lemairecarl hi,have you solve get the appropriate weights for dMaSIF search?thank you

**Comment by BJWiley233** [comment]
`convert_to_npy` is in this repo https://github.com/casperg92/MaSIF_colab/blob/main/data_preprocessing/download_pdb.py#L129
