### ISSUE TITLE
Cannot replicate results using benchmark scripts and provided model

### ISSUE THREAD

**Issue by lemairecarl** [FreyrS/dMaSIF#16]
Hi,
The model provided in `models/` does not match any that are used in the benchmarking scripts.
Also, the structure of the `state_dict` of the provided checkpoint does not match the structure of the model. It does not seem like this checkpoint was produced with this repo.

Consequently, the provided model does not help reproducing the results from the paper. Worse, it's only after having spent lots of time trying to get the code to work that we noticed this issue. At first glance, it looks like we have a pretrained model to work with; but sadly this is not the case.

**Comment by FreyrS** [comment]
Hi @lemairecarl,

dMaSIF has now been made easier to use through Google Colab, please check https://colab.research.google.com/github/casperg92/MaSIF_colab/blob/main/dMaSIF_Colab_V1.ipynb and see if it helps

**Comment by lemairecarl** [comment]
Hi, thanks a lot for this, it is helpful.

However, I do not agree with closing this issue, as we don't have appropriate weights for dMaSIF search.

**Comment by FreyrS** [comment]
Hi @lemairecarl,

I'm not quite sure why you're having problems with loading the model.
I don't have any problems with it on my computer.

Make sure you are providing the correct parameters on the command line. 
The model provided is called dMaSIF_search_3layer_12A_16dim, which means that it's the "search" problem, 3 convolutional layers, 12A sized patches and 16-dimensional point descriptors.
A corresponding command for running inference on the testing set would be: 
python -W ignore -u main_inference.py --experiment_name dMaSIF_search_3layer_12A_16dim --batch_size 64 --embedding_layer dMaSIF --search True --emb_dims 16 --device cuda:0 --radius 12.0 --n_layers 3

You can see in more detail all available parameters and their description in https://github.com/FreyrS/dMaSIF/blob/master/Arguments.py

**Comment by orange2350** [comment]
@lemairecarl hi，have you solved this problem? thank you
