### ISSUE TITLE
mesh ply files from masif preprocessing scripts were not  fed into atoms_to_points_normals

### ISSUE THREAD

**Issue by jiyanbio** [FreyrS/dMaSIF#19]
atoms_to_points_normals() function was decrbied clearly in your paper. But the trainning process by using mesh ply files from masif preprocessing scripts skipped it. 
My question is that, in the inference step, If such model directly took a pdb as the input which would be convert to points by atoms_to_points_normals() function, does it make sense when input files are different between training and inference?

**Comment by FreyrS** [comment]
Hi @jiyanbio,

dMaSIF calls atoms_to_points_normals() also during training and only extracts the interface labels from the mesh ply files. 
During training we simplified the process such that the surfaces are only generated before the first epoch and not during every epoch, see https://github.com/FreyrS/dMaSIF/blob/0dcc26c3c218a39d5fe26beb2e788b95fb028896/main_training.py#L55 , this line eventually leads to https://github.com/FreyrS/dMaSIF/blob/0dcc26c3c218a39d5fe26beb2e788b95fb028896/data_iteration.py#L126 where the surface of each protein is generated.
