### ISSUE TITLE
benchmark_scripts/

### ISSUE THREAD

**Issue by Jonas-Verhellen** [FreyrS/dMaSIF#2]
The readme   mentions that the command line options needed to reproduce the benchmarks can be found in benchmark_scripts/. Could it be that this folder is missing?

**Comment by jeanfeydy** [comment]
Hi @Jonas-Verhellen ,

Thanks for your remark!
@FreyrS has just uploaded it with the latest commit: all our apologies for the delay :-)

Best regards,
Jean
