### ISSUE TITLE
Site and Search do not output the same number of atoms

### ISSUE THREAD

**Issue by lemairecarl** [FreyrS/dMaSIF#21]
Hi,
I have successfully managed to predict on new pdbs using the provided weights. Thanks for providing them.

I am trying to perform a PPI search, so I need to run dMaSIF Site, and then Search. I have used the commands below:

```
python -W ignore -u main_inference.py --experiment_name dMaSIF_search_3layer_12A_16dim --batch_size 64 --embedding_layer dMaSIF --emb_dims 16 --device cuda:0 --radius 12.0 --n_layers 3 --npy_dir NPY_DIR --search True

python -W ignore -u main_inference.py --experiment_name dMaSIF_site_3layer_16dims_12A_100sup_epoch71 --batch_size 64 --embedding_layer dMaSIF --emb_dims 16 --device cuda:0 --radius 12.0 --n_layers 3 --npy_dir NPY_DIR --site True
```

I added `--npy_dir NPY_DIR` for my use case. Basically, it calls load_protein_pair on proteins from a folder, but it only fills the first protein of the pair.

**The problem is that for a single protein, the Site and Search predictions have a different number of rows!**

Here are my questions:

* Why does the dMaSIF site and search produce outputs with a different number of rows (atoms) ?
* Why does dMaSIF site outputs embeddings? How good are those for PPI search ? If I could use them, it would solve my problem, since I need an embedding and an inferface prediction for each atom.

Thanks!

**Comment by lemairecarl** [comment]
I found something. It's related to this line:

https://github.com/FreyrS/dMaSIF/blob/0dcc26c3c218a39d5fe26beb2e788b95fb028896/geometry_processing.py#L245

When I run dmasif **search** multiple times on the same input, this line is deterministic; the pseudo-random sampling gives the same values.

Also, when I run dmasif **site** multiple times, this line is deterministic.

**However, the sampling result from dmasif Search is NOT the same as the sampling result in dmasif Site!**

Since the sampling is different, the resulting point cloud is also different, and the points being kept differ. Thus, it explains why Search and Site output a different number of atoms.

My hypothesis is that Search uses the random number generator (RNG) a different number of times than Site. Thus, when arriving at the sampling, the RNG is in a different state. I am not sure which RNG is the culprit here (Numpy, torch, CUDA...)

I'm trying to see what the discrepancy is between Search and Site it terms of calling the RNG, but I didn't find anything yet. Right now, I'm trying running the code on CPU to see if it helps getting a deterministic result. I had to modify a few things to make it work. Sadly, it seems much too slow.

**Comment by FreyrS** [comment]
Hi @lemairecarl,

I assume you mean there are different number of points in the point clouds and not different number of atoms.
A way to go around this would be to precompute the surfaces using the atoms_to_points_normals function, then load them during inference and make search/site predictions on them.
