### ISSUE TITLE
main_inference result analysis

### ISSUE THREAD

**Issue by OtaviaW** [FreyrS/dMaSIF#28]
hi there, could you tell me how to visualize the .vtk file after I finished main_inference.py with a single PDB, and how to use the other .npy files.

**Comment by jeanfeydy** [comment]
Hi @OtaviaW ,

Apologies for the delay.
VTK files are best visualized with [Paraview](https://www.paraview.org/).
For a Python-friendly option, you may also use PyVista or Vedo.

With respect to the other .npy files, these are simple numerical arrays that you can load with [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.load.html). The names should be pretty explicit on the meaning of their values.

Best regards,
Jean
