### ISSUE TITLE
Interface Labels

### ISSUE THREAD

**Issue by chang-github-00** [FreyrS/dMaSIF#3]
The code use interface labels from the ply file. How is this "iface" item labeled ?
Also what is the function in data.py **iface_valid_filter** for ?
Thanks for your great work and neat code !
Best,
Chang

**Comment by FreyrS** [comment]
Hi Chang
The definition of the interface labels comes from our previous work on [MaSIF](https://www.nature.com/articles/s41592-019-0666-6)

_"**Definition of interface points in a protein surface**
We defined the ground truth interface as the region of the surface that becomes inaccessible to solvent molecules on complex formation. This was done by computing the surfaces of the complexes and the unbound partners. Surface regions in the individual partners that have no corresponding surface in the bound complex were then defined as the ground truth interface. Surface regions that become solvent inaccessible on complex formation were defined as the ground truth interface."_

The reasoning behind iface_valid_filter also comes from the same work and is just there to filter out interactions that are either to small (and could simply be crystal contacts or some other artefacts) or too big and overlap the whole surface of one of the binding partners.

And thanks!
