### ISSUE TITLE
Choice of the atom RADII

### ISSUE THREAD

**Issue by Ieremie** [FreyrS/dMaSIF#32]
Where do the following RADII values for the atoms come from?

`atomic_radii = torch.cuda.FloatTensor([170, 110, 152, 155, 180, 190], device=x.device)`

In the previous mesh based MASIF version, the following values are used for the MSMS program.
```
radii = {"N": "1.540000", "O": "1.400000", "C": "1.740000", "H": "1.200000", "S": "1.800000", "P": "1.800000",
         "Z": "1.39", "X": "0.770000"}
```

**Comment by jeanfeydy** [comment]
Hi @Ieremie ,

To be honest, I don't really remember... 
But the numbers line up with the "van der Waals" column on this [Wikipedia table](https://en.wikipedia.org/wiki/Atomic_radii_of_the_elements_(data_page)), so I assume that this is what we used?

Best regards and apologies for the long delay,
Jean
