### ISSUE TITLE
a tiny error in save_protein_batch_single

### ISSUE THREAD

**Issue by jiyanbio** [FreyrS/dMaSIF#4]
labels = P["labels"].view(-1, 1) if **_P1_**["labels"] is not None else 0.0 * predictions
P1 --> P, isn't it?

**Comment by jiyanbio** [comment]
another issue:
embedding = P["embedding_1"]   --> embedding = P["embedding_1"] if pdb_idx == 1 else P["embedding_2"]

**Comment by FreyrS** [comment]
Hey @jiyanbio, you are absolutely correct, I've fixed these errors now, thanks a lot!

Freyr
