### ISSUE TITLE
Does anyone have a docker image that can run this project? Can you share it with me?

### ISSUE THREAD

**Issue by camel2000** [FreyrS/dMaSIF#40]

**Comment by jeanfeydy** [comment]
Hi @camel2000,

Thanks for your interest in our work.
I don't know if @FreyrS can provide any help on this - he is the one who ran all of our experiments.

On my side, I can at least give you a pointer to the reference image of the KeOps library: https://hub.docker.com/r/getkeops/keops-full
It is described here: https://github.com/getkeops/keops/blob/main/Dockerfile
which explains how to setup PyTorch, KeOps, and (a subset of) PyG.

Best regards,
Jean

**Comment by camel2000** [comment]
The reply is a little late, because I have been busy with other things recently. Thank you very much for your help. This problem has been solved, and the project can start running smoothly @jeanfeydy

**Comment by jeanfeydy** [comment]
Perfect, thanks :-)

**Comment by orange2350** [comment]
@camel2000 您好，请问您在这个项目的site和search板块都能得到作者它们描述的auroc结果吗？我用了作者提供的该dMaSIF_search_3layer_12A_16dim进行search版本的推理，对他们的测试集进行推理，auroc只有0.55左右。请问您的结果是多少呀？谢谢，祝好
