### ISSUE TITLE
TypeError: argument of type 'method' is not iterable

### ISSUE THREAD

**Issue by Lsz-20** [FreyrS/dMaSIF#53]
Hello, when I try to train the dMaSIF_search with benchmark_scripts/dMaSIF_search.sh, but it shows:

Preprocessing training dataset
  0%|                                                                                                          | 0/4615 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main_training.py", line 55, in <module>
    train_dataset = iterate_surface_precompute(train_loader, net, args)
  File "/home/zcma02/Protein_Design/dMaSIF/data_iteration.py", line 427, in iterate_surface_precompute
    P1, P2 = process(args, protein_pair, net)
  File "/home/zcma02/Protein_Design/dMaSIF/data_iteration.py", line 124, in process
    P1 = process_single(protein_pair, chain_idx=1)
  File "/home/zcma02/Protein_Design/dMaSIF/data_iteration.py", line 20, in process_single
    with_mesh = "face_p1" in protein_pair.keys
TypeError: argument of type 'method' is not iterable
I checked the inputs are:train_loader, net and args,are all seems right?

**Comment by BJWiley233** [comment]
Newer python version require the `()` after a `dictionary.keys` so you need to make these [lines](https://github.com/FreyrS/dMaSIF/blob/0dcc26c3c218a39d5fe26beb2e788b95fb028896/data_iteration.py#L20-L21):

```
with_mesh = "face_p1" in protein_pair.keys()
preprocessed = "gen_xyz_p1" in protein_pair.keys()
```


And basically anywhere else there is a dictionary and dMaSIF is trying to access keys you will need to update.

**Comment by Lsz-20** [comment]
Thanks for your reply, it works well now!
