### ISSUE TITLE
save dmasif_search result

### ISSUE THREAD

**Issue by jiyanbio** [FreyrS/dMaSIF#8]
It's better to add some codes in the function 'def save_protein_batch_single (protein_pair_id, P, save_path, pdb_idx)' to save dmasif_search predictions such as 'sampled_preds' variable.

**Comment by FreyrS** [comment]
Hi @jiyanbio,
The point descriptors from dmasif_search are already saved in https://github.com/FreyrS/dMaSIF/blob/master/data_iteration.py#L87-L96. 
As for the variable sampled_preds it's only there to eventually compute the ROC-AUC for that particular sample.
