### ISSUE TITLE
Availability of '{pdb_id}_meshpoints.npy' data?

### ISSUE THREAD

**Issue by hypnopump** [FreyrS/dMaSIF#9]
Hi there!

Cool code! I trained a model following your scripts and i wanted to benchmark its performance with the provided notebooks. However, there's some data which is not available from `data_analysis/analyse_output.ipynb`.

```python
meshpoints = np.load(datafolder/(pdb_id+'_meshpoints.npy'))
````

How should I get the data mentioned here? 

Best, 
Eric Alcaide

**Comment by FreyrS** [comment]
Hi there and thanks!

The meshpoints are the points from our previous method (https://github.com/LPDI-EPFL/masif), you can extract them from the ply files in surface_data/raw/01-benchmark_surfaces.

**Comment by orange2350** [comment]
May I ask if you've solved it? By extracting using masif, does the author mean one of the files in the pre-calculated part using masif? Or is it something else? Thank you! @hypnopump
